// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "GitHub Issues",
            "url": "https://github.com/Amirbehzad11/geo-service/issues"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/gps/trip/{id}/location": {
            "get": {
                "description": "Returns the most recent GPS state for a trip, read from Redis. State is cached for 24 hours after the last update.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gps"
                ],
                "summary": "Get latest trip location",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Latest location state",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/geo-service_internal_response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/geo-service_internal_model.LocationState"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid trip ID",
                        "schema": {
                            "$ref": "#/definitions/geo-service_internal_response.Failure"
                        }
                    },
                    "404": {
                        "description": "No location found for this trip",
                        "schema": {
                            "$ref": "#/definitions/geo-service_internal_response.Failure"
                        }
                    }
                }
            }
        },
        "/gps/update": {
            "post": {
                "description": "Accepts a raw GPS position for an active trip. Applies rate limiting, EMA smoothing (α=0.75), speed computation, and cross-track deviation detection against the planned route. Writes state to Redis and broadcasts events via Redis Pub/Sub.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gps"
                ],
                "summary": "Process a GPS update",
                "parameters": [
                    {
                        "description": "GPS update payload",
                        "name": "update",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/geo-service_internal_model.GPSUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Processed location state",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/geo-service_internal_response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/geo-service_internal_model.LocationState"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Malformed JSON body",
                        "schema": {
                            "$ref": "#/definitions/geo-service_internal_response.Failure"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/geo-service_internal_response.Failure"
                        }
                    },
                    "429": {
                        "description": "Rate limited — update received too soon",
                        "schema": {
                            "$ref": "#/definitions/geo-service_internal_response.Failure"
                        }
                    },
                    "500": {
                        "description": "Internal processing error",
                        "schema": {
                            "$ref": "#/definitions/geo-service_internal_response.Failure"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the service health status and the reachability of each downstream dependency. Returns HTTP 503 when any required dependency is unreachable.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "All dependencies healthy",
                        "schema": {
                            "$ref": "#/definitions/geo-service_internal_response.Success"
                        }
                    },
                    "503": {
                        "description": "One or more dependencies unreachable",
                        "schema": {
                            "$ref": "#/definitions/geo-service_internal_response.Failure"
                        }
                    }
                }
            }
        },
        "/route": {
            "post": {
                "description": "Computes the fastest route between two coordinates using A* search over the OSM road graph, with Yen's k-shortest-paths algorithm for alternative routes. Falls back to Haversine straight-line when the endpoints are outside graph coverage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routing"
                ],
                "summary": "Calculate a route",
                "parameters": [
                    {
                        "description": "Route request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/geo-service_internal_model.RouteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Route calculated successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/geo-service_internal_response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/geo-service_internal_model.RouteResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Malformed JSON body",
                        "schema": {
                            "$ref": "#/definitions/geo-service_internal_response.Failure"
                        }
                    },
                    "422": {
                        "description": "Validation error (invalid coordinates or transport mode)",
                        "schema": {
                            "$ref": "#/definitions/geo-service_internal_response.Failure"
                        }
                    },
                    "500": {
                        "description": "Internal routing error",
                        "schema": {
                            "$ref": "#/definitions/geo-service_internal_response.Failure"
                        }
                    }
                }
            }
        },
        "/ws/trip/{id}": {
            "get": {
                "description": "Upgrades the connection to WebSocket and streams real-time ` + "`" + `location.updated` + "`" + ` and ` + "`" + `deviation.detected` + "`" + ` events for the specified trip via Redis Pub/Sub. Send any message to keep the connection alive.",
                "tags": [
                    "websocket"
                ],
                "summary": "WebSocket — live trip events",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols — WebSocket upgrade successful"
                    },
                    "400": {
                        "description": "Missing or invalid trip ID",
                        "schema": {
                            "$ref": "#/definitions/geo-service_internal_response.Failure"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "geo-service_internal_model.GPSUpdate": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "timestamp": {
                    "description": "Unix seconds",
                    "type": "integer"
                },
                "trip_id": {
                    "type": "integer"
                }
            }
        },
        "geo-service_internal_model.LocationState": {
            "type": "object",
            "properties": {
                "deviation_km": {
                    "description": "distance from planned route",
                    "type": "number"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "speed_kmh": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                },
                "trip_id": {
                    "type": "integer"
                }
            }
        },
        "geo-service_internal_model.RouteOption": {
            "type": "object",
            "properties": {
                "distance_km": {
                    "type": "number"
                },
                "duration_min": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "is_primary": {
                    "type": "boolean"
                },
                "mode": {
                    "type": "string"
                },
                "polyline": {
                    "type": "string"
                }
            }
        },
        "geo-service_internal_model.RouteRequest": {
            "type": "object",
            "properties": {
                "alternatives": {
                    "description": "requested route count, clamped server-side",
                    "type": "integer"
                },
                "end_lat": {
                    "type": "number"
                },
                "end_lng": {
                    "type": "number"
                },
                "mode": {
                    "description": "car | motorcycle | bus | walking | airplane (default: car)",
                    "type": "string"
                },
                "start_lat": {
                    "type": "number"
                },
                "start_lng": {
                    "type": "number"
                },
                "trip_id": {
                    "description": "optional",
                    "type": "integer"
                },
                "vehicle_type": {
                    "description": "alias for mode, useful for Laravel payloads",
                    "type": "string"
                }
            }
        },
        "geo-service_internal_model.RouteResponse": {
            "type": "object",
            "properties": {
                "distance": {
                    "description": "Backward-compatible primary route fields.",
                    "type": "number"
                },
                "duration": {
                    "description": "minutes",
                    "type": "number"
                },
                "mode": {
                    "type": "string"
                },
                "polyline": {
                    "description": "Google Encoded Polyline",
                    "type": "string"
                },
                "primary": {
                    "$ref": "#/definitions/geo-service_internal_model.RouteOption"
                },
                "routes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/geo-service_internal_model.RouteOption"
                    }
                }
            }
        },
        "geo-service_internal_response.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "geo-service_internal_response.Failure": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/geo-service_internal_response.ErrorDetail"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "geo-service_internal_response.Success": {
            "type": "object",
            "properties": {
                "data": {},
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "geo-service",
	Description:      "A production-ready geospatial routing microservice with a custom A* + Yen's k-shortest-paths algorithm, live GPS tracking, WebSocket event delivery, and a PostGIS-backed OSM road graph.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
